--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Faizx511x/BedWars-Hypixel
build-by-default: true
branches:
- master
projects:
  BedWars-Hypixel:
    path: ""
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.2
...
